import { Student, Teacher, UserRole, TeacherStatus } from './types';

export const MOCK_TEACHERS: Teacher[] = [
  {
    teacherId: 'T001',
    fullName: 'Dr. Evelyn Reed',
    phone: '555-0101',
    email: 'evelyn.reed@school.edu',
    designation: 'Professor of Physics',
    department: 'Physics',
    qualification: 'Ph.D. in Physics',
    experience: 15,
    joiningDate: '01/08/2009',
    dateOfBirth: '12/05/1978',
    subjects: ['Quantum Mechanics', 'Thermodynamics', 'Modern Physics'],
    education: [
      {
        degree: 'Ph.D. in Theoretical Physics',
        college: 'Massachusetts Institute of Technology',
        university: 'MIT',
        year: '2009',
      },
      {
        degree: 'M.Sc. in Physics',
        college: 'Stanford University',
        university: 'Stanford',
        year: '2004',
      },
      {
        degree: 'B.Sc. in Physics',
        college: 'University of California, Berkeley',
        university: 'UC Berkeley',
        year: '2002',
      },
    ],
    bio: 'Dr. Evelyn Reed is a distinguished physicist with over 15 years of teaching and research experience. Her research focuses on quantum mechanics and particle physics. She has mentored numerous students who have gone on to pursue successful careers in physics and engineering.',
    specializations: ['Quantum Computing', 'Particle Physics', 'Theoretical Physics'],
    officeHours: 'Mon-Fri: 2:00 PM - 4:00 PM',
    achievements: [
      {
        title: 'Best Teacher Award',
        description: 'Awarded for excellence in teaching and student mentorship',
        year: '2022',
        issuedBy: 'University Board'
      },
      {
        title: 'Outstanding Research Contribution',
        description: 'Recognized for significant contributions to quantum physics research',
        year: '2021',
        issuedBy: 'Physics Association'
      }
    ],
    research: [
      {
        title: 'Quantum Entanglement in Multi-Particle Systems',
        journal: 'Journal of Quantum Physics',
        year: '2023',
        link: 'https://example.com/quantum-entanglement',
        authors: ['Evelyn Reed']
      },
      {
        title: 'Applications of Quantum Computing in Cryptography',
        journal: 'Physics Today',
        year: '2022',
        link: 'https://example.com/quantum-crypto',
        authors: ['Evelyn Reed', 'John Smith']
      }
    ],
    projects: [
      {
        title: 'Quantum Computing Research Initiative',
        description: 'A multi-year research project exploring practical applications of quantum computing',
        year: '2020-2024',
        role: 'Principal Investigator',
        fundingAgency: 'National Science Foundation'
      },
      {
        title: 'Particle Physics Education Program',
        description: 'Developing new curriculum and teaching methods for particle physics',
        year: '2021-2023',
        role: 'Co-Investigator'
      },
      {
        title: 'Student Physics Laboratory Modernization',
        description: 'Spearheaded the upgrade of undergraduate physics labs with state-of-the-art equipment and virtual simulation tools.',
        year: '2022-Present',
        role: 'Project Lead'
      }
    ],
    staffRoom: 'A-201',
    seatNo: '12',
    floor: '2nd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Evelyn',
  },
  {
    teacherId: 'T002',
    fullName: 'Mr. Samuel Chen',
    phone: '555-0102',
    email: 'samuel.chen@school.edu',
    designation: 'Mathematics Department Head',
    department: 'Mathematics',
    qualification: 'M.Sc. Mathematics',
    experience: 12,
    joiningDate: '15/06/2012',
    dateOfBirth: '08/03/1982',
    subjects: ['Calculus', 'Linear Algebra', 'Statistics'],
    education: [
      {
        degree: 'M.Sc. in Mathematics',
        college: 'Harvard University',
        university: 'Harvard',
        year: '2012',
      },
      {
        degree: 'B.Sc. in Mathematics',
        college: 'University of Chicago',
        university: 'UChicago',
        year: '2008',
      },
    ],
    bio: 'Samuel Chen is an accomplished mathematician specializing in applied mathematics and statistics. He has published numerous papers on mathematical modeling and has been instrumental in developing the university\'s advanced mathematics curriculum.',
    specializations: ['Applied Mathematics', 'Statistical Analysis', 'Mathematical Modeling'],
    officeHours: 'Mon-Fri: 9:00 AM - 11:00 AM',
    achievements: [
      {
        title: 'Excellence in Teaching Award',
        description: 'Recognized for innovative teaching methods in mathematics',
        year: '2020',
        issuedBy: 'Mathematics Association'
      }
    ],
    staffRoom: 'B-105',
    seatNo: '3',
    floor: '1st',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Samuel',
  },
  {
    teacherId: 'T003',
    fullName: 'Ms. Clara Oswald',
    phone: '555-0103',
    email: 'clara.oswald@school.edu',
    designation: 'English Literature Lecturer',
    department: 'English',
    qualification: 'M.A. English Literature',
    experience: 8,
    joiningDate: '20/08/2016',
    dateOfBirth: '15/11/1988',
    subjects: ['Shakespeare', 'Modern Poetry', 'Creative Writing'],
    education: [
      {
        degree: 'M.A. in English Literature',
        college: 'Oxford University',
        university: 'Oxford',
        year: '2016',
      },
      {
        degree: 'B.A. in English',
        college: 'Cambridge University',
        university: 'Cambridge',
        year: '2012',
      },
    ],
    bio: 'Clara Oswald is a passionate literature enthusiast who brings classic and contemporary works to life in her classroom. She has organized numerous literary festivals and poetry readings on campus.',
    specializations: ['Victorian Literature', 'Contemporary Poetry', 'Creative Writing'],
    officeHours: 'Tue-Thu: 3:00 PM - 5:00 PM',
    achievements: [],
    staffRoom: 'C-310',
    seatNo: '8',
    floor: '3rd',
    status: TeacherStatus.ON_BREAK,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Clara',
  },
  {
    teacherId: 'T004',
    fullName: 'Dr. Arthur Dent',
    phone: '555-0104',
    email: 'arthur.dent@school.edu',
    designation: 'History Professor',
    department: 'History',
    qualification: 'Ph.D. in History',
    experience: 20,
    joiningDate: '10/01/2004',
    dateOfBirth: '22/07/1975',
    subjects: ['World History', 'Ancient Civilizations', 'Modern History'],
    education: [
      {
        degree: 'Ph.D. in History',
        college: 'Yale University',
        university: 'Yale',
        year: '2004',
      },
      {
        degree: 'M.A. in History',
        college: 'Princeton University',
        university: 'Princeton',
        year: '1999',
      },
      {
        degree: 'B.A. in History',
        college: 'Brown University',
        university: 'Brown',
        year: '1997',
      },
    ],
    bio: 'Dr. Arthur Dent is a renowned historian with expertise in ancient civilizations and world history. He has led archaeological expeditions and published extensively on ancient trade routes.',
    specializations: ['Ancient Civilizations', 'Maritime History', 'Cultural Exchange'],
    officeHours: 'Mon-Wed-Fri: 10:00 AM - 12:00 PM',
    achievements: [
      {
        title: 'Distinguished Historian Award',
        description: 'Lifetime achievement award for contributions to historical research',
        year: '2023',
        issuedBy: 'Historical Society'
      }
    ],
    staffRoom: 'A-205',
    seatNo: '5',
    floor: '2nd',
    status: TeacherStatus.ON_HOLIDAY,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arthur',
  },
  {
    teacherId: 'T005',
    fullName: 'Dr. Maya Patel',
    phone: '555-0105',
    email: 'maya.patel@school.edu',
    designation: 'Computer Science Professor',
    department: 'Computer Science',
    qualification: 'Ph.D. in Computer Science',
    experience: 10,
    joiningDate: '05/09/2014',
    dateOfBirth: '18/04/1984',
    subjects: ['Data Structures', 'Algorithms', 'Machine Learning'],
    education: [
      {
        degree: 'Ph.D. in Computer Science',
        college: 'Carnegie Mellon University',
        university: 'CMU',
        year: '2014',
      },
      {
        degree: 'M.S. in Computer Science',
        college: 'Georgia Tech',
        university: 'Georgia Tech',
        year: '2010',
      },
      {
        degree: 'B.Tech in Computer Science',
        college: 'IIT Bombay',
        university: 'IIT Bombay',
        year: '2008',
      },
    ],
    bio: 'Dr. Maya Patel is a leading expert in artificial intelligence and machine learning. She has worked on various industry projects and brings real-world experience to her teaching.',
    specializations: ['Machine Learning', 'Artificial Intelligence', 'Data Science'],
    officeHours: 'Mon-Fri: 11:00 AM - 1:00 PM',
    achievements: [
      {
        title: 'Innovation in Teaching Award',
        description: 'Recognized for integrating industry practices into curriculum',
        year: '2022',
        issuedBy: 'Computer Science Board'
      }
    ],
    research: [
      {
        title: 'Deep Learning Applications in Healthcare',
        journal: 'Journal of AI Research',
        year: '2023',
        authors: ['Maya Patel', 'Sarah Johnson']
      }
    ],
    staffRoom: 'B-201',
    seatNo: '15',
    floor: '2nd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maya',
  },
  {
    teacherId: 'T006',
    fullName: 'Prof. James Wilson',
    phone: '555-0106',
    email: 'james.wilson@school.edu',
    designation: 'Chemistry Professor',
    department: 'Chemistry',
    qualification: 'Ph.D. in Chemistry',
    experience: 18,
    joiningDate: '12/03/2006',
    dateOfBirth: '30/09/1976',
    subjects: ['Organic Chemistry', 'Inorganic Chemistry', 'Physical Chemistry'],
    education: [
      {
        degree: 'Ph.D. in Organic Chemistry',
        college: 'University of California, Los Angeles',
        university: 'UCLA',
        year: '2006',
      },
      {
        degree: 'M.Sc. in Chemistry',
        college: 'University of Michigan',
        university: 'UMich',
        year: '2002',
      },
      {
        degree: 'B.Sc. in Chemistry',
        college: 'University of Texas at Austin',
        university: 'UT Austin',
        year: '2000',
      },
    ],
    bio: 'Professor James Wilson has extensive experience in organic synthesis and green chemistry. He has developed several patented chemical processes and actively mentors graduate students.',
    specializations: ['Organic Synthesis', 'Green Chemistry', 'Medicinal Chemistry'],
    officeHours: 'Tue-Thu: 1:00 PM - 3:00 PM',
    achievements: [
      {
        title: 'Patent Award',
        description: 'Multiple patents in organic synthesis methodologies',
        year: '2021',
        issuedBy: 'US Patent Office'
      }
    ],
    staffRoom: 'A-301',
    seatNo: '7',
    floor: '3rd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
  },
  {
    teacherId: 'T007',
    fullName: 'Ms. Sophia Martinez',
    phone: '555-0107',
    email: 'sophia.martinez@school.edu',
    designation: 'Biology Lecturer',
    department: 'Biology',
    qualification: 'M.Sc. Biology',
    experience: 7,
    joiningDate: '18/07/2017',
    dateOfBirth: '25/12/1989',
    subjects: ['Genetics', 'Microbiology', 'Ecology'],
    education: [
      {
        degree: 'M.Sc. in Biology',
        college: 'University of Washington',
        university: 'UW',
        year: '2017',
      },
      {
        degree: 'B.Sc. in Biology',
        college: 'University of Oregon',
        university: 'UO',
        year: '2013',
      },
    ],
    bio: 'Sophia Martinez is a dedicated biology educator with a passion for environmental science. She coordinates field trips and research projects that connect classroom learning with real-world applications.',
    specializations: ['Molecular Biology', 'Environmental Science', 'Biotechnology'],
    officeHours: 'Mon-Wed-Fri: 9:00 AM - 11:00 AM',
    achievements: [],
    staffRoom: 'C-205',
    seatNo: '11',
    floor: '2nd',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sophia',
  },
  {
    teacherId: 'T008',
    fullName: 'Dr. Raj Kumar',
    phone: '555-0108',
    email: 'raj.kumar@school.edu',
    designation: 'Mechanical Engineering Professor',
    department: 'Mechanical Engineering',
    qualification: 'Ph.D. in Mechanical Engineering',
    experience: 14,
    joiningDate: '22/02/2010',
    dateOfBirth: '10/06/1980',
    subjects: ['Thermodynamics', 'Fluid Mechanics', 'Machine Design'],
    education: [
      {
        degree: 'Ph.D. in Mechanical Engineering',
        college: 'Purdue University',
        university: 'Purdue',
        year: '2010',
      },
      {
        degree: 'M.S. in Mechanical Engineering',
        college: 'University of Illinois',
        university: 'UIUC',
        year: '2006',
      },
      {
        degree: 'B.Tech in Mechanical Engineering',
        college: 'IIT Delhi',
        university: 'IIT Delhi',
        year: '2004',
      },
    ],
    bio: 'Dr. Raj Kumar is a mechanical engineering expert specializing in thermal systems and renewable energy. He has collaborated with industry partners on sustainable technology development.',
    specializations: ['Thermal Engineering', 'Renewable Energy', 'CAD/CAM'],
    officeHours: 'Mon-Fri: 3:00 PM - 5:00 PM',
    staffRoom: 'B-310',
    seatNo: '20',
    floor: '3rd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Raj',
    achievements: []
  },
  {
    teacherId: 'T009',
    fullName: 'Ms. Emily Brown',
    phone: '555-0109',
    email: 'emily.brown@school.edu',
    designation: 'Economics Lecturer',
    department: 'Economics',
    qualification: 'M.A. Economics',
    experience: 6,
    joiningDate: '30/08/2018',
    dateOfBirth: '14/02/1991',
    subjects: ['Microeconomics', 'Macroeconomics', 'International Trade'],
    education: [
      {
        degree: 'M.A. in Economics',
        college: 'London School of Economics',
        university: 'LSE',
        year: '2018',
      },
      {
        degree: 'B.A. in Economics',
        college: 'University of Edinburgh',
        university: 'Edinburgh',
        year: '2014',
      },
    ],
    bio: 'Emily Brown brings fresh perspectives to economics education, focusing on behavioral economics and international trade. She has experience working with international organizations.',
    specializations: ['Behavioral Economics', 'International Trade', 'Development Economics'],
    officeHours: 'Tue-Thu: 10:00 AM - 12:00 PM',
    achievements: [],
    staffRoom: 'A-110',
    seatNo: '4',
    floor: '1st',
    status: TeacherStatus.ON_BREAK,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
  },
  {
    teacherId: 'T010',
    fullName: 'Dr. Ahmed Hassan',
    phone: '555-0110',
    email: 'ahmed.hassan@school.edu',
    designation: 'Electrical Engineering Professor',
    department: 'Electrical Engineering',
    qualification: 'Ph.D. in Electrical Engineering',
    experience: 16,
    joiningDate: '08/04/2008',
    dateOfBirth: '05/08/1978',
    subjects: ['Circuit Theory', 'Power Systems', 'Control Systems'],
    education: [
      {
        degree: 'Ph.D. in Electrical Engineering',
        college: 'Stanford University',
        university: 'Stanford',
        year: '2008',
      },
      {
        degree: 'M.S. in Electrical Engineering',
        college: 'UC Berkeley',
        university: 'UC Berkeley',
        year: '2004',
      },
      {
        degree: 'B.E. in Electrical Engineering',
        college: 'IIT Madras',
        university: 'IIT Madras',
        year: '2002',
      },
    ],
    bio: 'Dr. Ahmed Hassan is a pioneer in smart grid technology and power electronics. He has consulted for major utility companies and holds several patents in power system optimization.',
    specializations: ['Power Systems', 'Smart Grid', 'Power Electronics'],
    officeHours: 'Mon-Wed-Fri: 2:00 PM - 4:00 PM',
    achievements: [
      {
        title: 'IEEE Fellow',
        description: 'Elected Fellow of the Institute of Electrical and Electronics Engineers',
        year: '2020',
        issuedBy: 'IEEE'
      }
    ],
    staffRoom: 'B-405',
    seatNo: '18',
    floor: '4th',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmed',
  },
  {
    teacherId: 'T011',
    fullName: 'Prof. Linda Garcia',
    phone: '555-0111',
    email: 'linda.garcia@school.edu',
    designation: 'Psychology Professor',
    department: 'Psychology',
    qualification: 'Ph.D. in Psychology',
    experience: 11,
    joiningDate: '15/09/2013',
    dateOfBirth: '28/01/1983',
    subjects: ['Cognitive Psychology', 'Social Psychology', 'Research Methods'],
    education: [
      {
        degree: 'Ph.D. in Clinical Psychology',
        college: 'University of Pennsylvania',
        university: 'UPenn',
        year: '2013',
      },
      {
        degree: 'M.A. in Psychology',
        college: 'Northwestern University',
        university: 'Northwestern',
        year: '2009',
      },
      {
        degree: 'B.A. in Psychology',
        college: 'University of Wisconsin',
        university: 'UW-Madison',
        year: '2007',
      },
    ],
    bio: 'Professor Linda Garcia specializes in cognitive psychology and mental health research. She has published extensively on cognitive behavioral therapy and mindfulness practices.',
    specializations: ['Cognitive Psychology', 'Clinical Psychology', 'Mental Health'],
    officeHours: 'Mon-Fri: 10:00 AM - 12:00 PM',
    staffRoom: 'C-115',
    seatNo: '9',
    floor: '1st',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Linda',
    achievements: []
  },
  {
    teacherId: 'T012',
    fullName: 'Mr. David Lee',
    phone: '555-0112',
    email: 'david.lee@school.edu',
    designation: 'Civil Engineering Lecturer',
    department: 'Civil Engineering',
    qualification: 'M.Tech Civil Engineering',
    experience: 9,
    joiningDate: '25/11/2015',
    dateOfBirth: '12/10/1986',
    subjects: ['Structural Analysis', 'Concrete Technology', 'Surveying'],
    education: [
      {
        degree: 'M.Tech in Civil Engineering',
        college: 'IIT Roorkee',
        university: 'IIT Roorkee',
        year: '2015',
      },
      {
        degree: 'B.Tech in Civil Engineering',
        college: 'NIT Trichy',
        university: 'NIT Trichy',
        year: '2011',
      },
    ],
    bio: 'David Lee is a civil engineering expert with practical experience in infrastructure development. He has worked on major construction projects and brings real-world insights to his teaching.',
    specializations: ['Structural Engineering', 'Construction Management', 'Sustainable Infrastructure'],
    officeHours: 'Tue-Thu: 2:00 PM - 4:00 PM',
    achievements: [],
    staffRoom: 'B-215',
    seatNo: '14',
    floor: '2nd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
  },
  {
    teacherId: 'T013',
    fullName: 'Dr. Priya Sharma',
    phone: '555-0113',
    email: 'priya.sharma@school.edu',
    designation: 'Business Administration Professor',
    department: 'Business Administration',
    qualification: 'Ph.D. in Business Administration',
    experience: 13,
    joiningDate: '03/05/2011',
    dateOfBirth: '20/03/1981',
    subjects: ['Marketing Management', 'Strategic Management', 'Entrepreneurship'],
    education: [
      {
        degree: 'Ph.D. in Business Administration',
        college: 'INSEAD',
        university: 'INSEAD',
        year: '2011',
      },
      {
        degree: 'MBA',
        college: 'IIM Ahmedabad',
        university: 'IIM Ahmedabad',
        year: '2007',
      },
      {
        degree: 'B.Com',
        college: 'Delhi University',
        university: 'DU',
        year: '2005',
      },
    ],
    bio: 'Dr. Priya Sharma is a business administration expert with extensive corporate experience. She has consulted for Fortune 500 companies and specializes in strategic management and entrepreneurship.',
    specializations: ['Strategic Management', 'Marketing Strategy', 'Entrepreneurship'],
    officeHours: 'Mon-Wed-Fri: 11:00 AM - 1:00 PM',
    achievements: [],
    staffRoom: 'A-320',
    seatNo: '6',
    floor: '3rd',
    status: TeacherStatus.UNAVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
  },
  {
    teacherId: 'T014',
    fullName: 'Mr. Robert Taylor',
    phone: '555-0114',
    email: 'robert.taylor@school.edu',
    designation: 'Physical Education Instructor',
    department: 'Physical Education',
    qualification: 'M.P.Ed',
    experience: 8,
    joiningDate: '10/07/2016',
    dateOfBirth: '16/05/1988',
    subjects: ['Sports Science', 'Fitness Training', 'Yoga'],
    education: [
      {
        degree: 'M.P.Ed',
        college: 'LNIPE Gwalior',
        university: 'LNIPE',
        year: '2016',
      },
      {
        degree: 'B.P.Ed',
        college: 'Lakshmibai National College',
        university: 'LNCPE',
        year: '2012',
      },
    ],
    bio: 'Robert Taylor is a certified fitness trainer and sports science expert. He has represented the state in national-level athletic competitions and promotes holistic wellness among students.',
    specializations: ['Sports Psychology', 'Athletic Training', 'Nutrition'],
    officeHours: 'Mon-Fri: 7:00 AM - 9:00 AM',
    achievements: [],
    staffRoom: 'Sports Complex',
    seatNo: '1',
    floor: 'Ground',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Robert',
  },
  {
    teacherId: 'T015',
    fullName: 'Dr. Nina Patel',
    phone: '555-0115',
    email: 'nina.patel@school.edu',
    designation: 'Philosophy Professor',
    department: 'Philosophy',
    qualification: 'Ph.D. in Philosophy',
    experience: 15,
    joiningDate: '01/02/2009',
    dateOfBirth: '07/11/1979',
    subjects: ['Ethics', 'Logic', 'Eastern Philosophy'],
    education: [
      {
        degree: 'Ph.D. in Philosophy',
        college: 'University of Toronto',
        university: 'UofT',
        year: '2009',
      },
      {
        degree: 'M.A. in Philosophy',
        college: 'McGill University',
        university: 'McGill',
        year: '2005',
      },
      {
        degree: 'B.A. in Philosophy',
        college: 'University of British Columbia',
        university: 'UBC',
        year: '2003',
      },
    ],
    bio: 'Dr. Nina Patel is a distinguished philosopher specializing in ethics and Eastern philosophy. She has published widely on comparative philosophy and leads meditation workshops for students.',
    specializations: ['Ethics', 'Eastern Philosophy', 'Philosophy of Mind'],
    officeHours: 'Tue-Thu: 3:00 PM - 5:00 PM',
    achievements: [
      {
        title: 'Philosophy Book Award',
        description: 'Awarded for outstanding contribution to philosophical literature',
        year: '2022',
        issuedBy: 'Philosophy Association'
      }
    ],
    staffRoom: 'C-410',
    seatNo: '13',
    floor: '4th',
    status: TeacherStatus.ON_BREAK,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Nina',
  },
  {
    teacherId: 'T016',
    fullName: 'Dr. Michael Thompson',
    phone: '555-0116',
    email: 'michael.thompson@school.edu',
    designation: 'Statistics Professor',
    department: 'Statistics',
    qualification: 'Ph.D. in Statistics',
    experience: 12,
    joiningDate: '15/08/2012',
    dateOfBirth: '03/06/1982',
    subjects: ['Probability Theory', 'Statistical Inference', 'Data Analysis'],
    education: [
      {
        degree: 'Ph.D. in Statistics',
        college: 'University of Chicago',
        university: 'UChicago',
        year: '2012',
      },
      {
        degree: 'M.S. in Statistics',
        college: 'University of Michigan',
        university: 'UMich',
        year: '2008',
      },
      {
        degree: 'B.S. in Mathematics',
        college: 'University of Minnesota',
        university: 'UMN',
        year: '2006',
      },
    ],
    bio: 'Dr. Michael Thompson is a statistical expert specializing in Bayesian methods and machine learning applications. He has consulted for government agencies on data-driven policy decisions.',
    specializations: ['Bayesian Statistics', 'Machine Learning', 'Statistical Computing'],
    officeHours: 'Mon-Wed-Fri: 1:00 PM - 3:00 PM',
    achievements: [
      {
        title: 'Outstanding Researcher Award',
        description: 'Recognized for contributions to statistical methodology',
        year: '2021',
        issuedBy: 'Statistics Association'
      }
    ],
    staffRoom: 'B-108',
    seatNo: '2',
    floor: '1st',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
  },
  {
    teacherId: 'T017',
    fullName: 'Ms. Jennifer Adams',
    phone: '555-0117',
    email: 'jennifer.adams@school.edu',
    designation: 'Fine Arts Instructor',
    department: 'Fine Arts',
    qualification: 'M.F.A',
    experience: 10,
    joiningDate: '20/09/2014',
    dateOfBirth: '25/04/1984',
    subjects: ['Drawing', 'Painting', 'Digital Art'],
    education: [
      {
        degree: 'M.F.A in Fine Arts',
        college: 'Rhode Island School of Design',
        university: 'RISD',
        year: '2014',
      },
      {
        degree: 'B.F.A in Visual Arts',
        college: 'California College of the Arts',
        university: 'CCA',
        year: '2010',
      },
    ],
    bio: 'Jennifer Adams is a contemporary artist and educator who has exhibited her work in galleries across the country. She specializes in digital art and multimedia installations.',
    specializations: ['Digital Art', 'Contemporary Painting', 'Art Theory'],
    officeHours: 'Tue-Thu: 2:00 PM - 4:00 PM',
    achievements: [
      {
        title: 'Artist Residency Award',
        description: 'Selected for prestigious artist residency program',
        year: '2023',
        issuedBy: 'National Arts Council'
      }
    ],
    staffRoom: 'Art Studio',
    seatNo: '1',
    floor: 'Ground',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jennifer',
  },
  {
    teacherId: 'T018',
    fullName: 'Dr. Kevin Zhang',
    phone: '555-0118',
    email: 'kevin.zhang@school.edu',
    designation: 'Chemical Engineering Professor',
    department: 'Chemical Engineering',
    qualification: 'Ph.D. in Chemical Engineering',
    experience: 14,
    joiningDate: '12/03/2010',
    dateOfBirth: '18/07/1980',
    subjects: ['Process Control', 'Reaction Engineering', 'Mass Transfer'],
    education: [
      {
        degree: 'Ph.D. in Chemical Engineering',
        college: 'MIT',
        university: 'MIT',
        year: '2010',
      },
      {
        degree: 'M.S. in Chemical Engineering',
        college: 'Caltech',
        university: 'Caltech',
        year: '2006',
      },
      {
        degree: 'B.Tech in Chemical Engineering',
        college: 'IIT Kanpur',
        university: 'IIT Kanpur',
        year: '2004',
      },
    ],
    bio: 'Dr. Kevin Zhang is a chemical engineering expert with extensive industrial experience in petrochemical processing. He holds multiple patents in catalytic processes.',
    specializations: ['Catalysis', 'Process Optimization', 'Petrochemical Engineering'],
    officeHours: 'Mon-Fri: 10:00 AM - 12:00 PM',
    achievements: [
      {
        title: 'Innovation Patent Award',
        description: 'Multiple patents in chemical process optimization',
        year: '2022',
        issuedBy: 'Chemical Engineering Society'
      }
    ],
    staffRoom: 'A-308',
    seatNo: '10',
    floor: '3rd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kevin',
  },
  {
    teacherId: 'T019',
    fullName: 'Prof. Maria Rodriguez',
    phone: '555-0119',
    email: 'maria.rodriguez@school.edu',
    designation: 'Political Science Professor',
    department: 'Political Science',
    qualification: 'Ph.D. in Political Science',
    experience: 16,
    joiningDate: '05/01/2008',
    dateOfBirth: '30/08/1978',
    subjects: ['International Relations', 'Comparative Politics', 'Public Policy'],
    education: [
      {
        degree: 'Ph.D. in Political Science',
        college: 'Harvard University',
        university: 'Harvard',
        year: '2008',
      },
      {
        degree: 'M.A. in International Relations',
        college: 'Columbia University',
        university: 'Columbia',
        year: '2004',
      },
      {
        degree: 'B.A. in Political Science',
        college: 'Georgetown University',
        university: 'Georgetown',
        year: '2002',
      },
    ],
    bio: 'Professor Maria Rodriguez is an expert in international relations and public policy. She has served as a policy advisor to government officials and international organizations.',
    specializations: ['International Relations', 'Public Policy', 'Latin American Politics'],
    officeHours: 'Mon-Wed-Fri: 3:00 PM - 5:00 PM',
    achievements: [
      {
        title: 'Policy Leadership Award',
        description: 'Recognized for contributions to public policy development',
        year: '2023',
        issuedBy: 'Policy Institute'
      }
    ],
    staffRoom: 'C-312',
    seatNo: '7',
    floor: '3rd',
    status: TeacherStatus.ON_BREAK,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria',
  },
  {
    teacherId: 'T020',
    fullName: 'Dr. Sarah Johnson',
    phone: '555-0120',
    email: 'sarah.johnson@school.edu',
    designation: 'Biochemistry Professor',
    department: 'Biochemistry',
    qualification: 'Ph.D. in Biochemistry',
    experience: 11,
    joiningDate: '22/08/2013',
    dateOfBirth: '14/12/1983',
    subjects: ['Protein Chemistry', 'Metabolism', 'Molecular Biology'],
    education: [
      {
        degree: 'Ph.D. in Biochemistry',
        college: 'Johns Hopkins University',
        university: 'JHU',
        year: '2013',
      },
      {
        degree: 'M.S. in Biochemistry',
        college: 'University of California, San Francisco',
        university: 'UCSF',
        year: '2009',
      },
      {
        degree: 'B.S. in Chemistry',
        college: 'University of North Carolina',
        university: 'UNC',
        year: '2007',
      },
    ],
    bio: 'Dr. Sarah Johnson is a biochemist specializing in protein structure and function. Her research has contributed to drug development for metabolic disorders.',
    specializations: ['Protein Biochemistry', 'Structural Biology', 'Drug Discovery'],
    officeHours: 'Tue-Thu: 9:00 AM - 11:00 AM',
    achievements: [
      {
        title: 'Research Excellence Award',
        description: 'Outstanding contributions to biochemical research',
        year: '2022',
        issuedBy: 'Biochemistry Society'
      }
    ],
    staffRoom: 'A-209',
    seatNo: '16',
    floor: '2nd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  },
  {
    teacherId: 'T021',
    fullName: 'Dr. Alexander Kim',
    phone: '555-0121',
    email: 'alexander.kim@school.edu',
    designation: 'Aerospace Engineering Professor',
    department: 'Aerospace Engineering',
    qualification: 'Ph.D. in Aerospace Engineering',
    experience: 13,
    joiningDate: '18/06/2011',
    dateOfBirth: '22/09/1981',
    subjects: ['Aerodynamics', 'Propulsion Systems', 'Spacecraft Design'],
    education: [
      {
        degree: 'Ph.D. in Aerospace Engineering',
        college: 'California Institute of Technology',
        university: 'Caltech',
        year: '2011',
      },
      {
        degree: 'M.S. in Aerospace Engineering',
        college: 'University of Michigan',
        university: 'UMich',
        year: '2007',
      },
      {
        degree: 'B.S. in Aerospace Engineering',
        college: 'Purdue University',
        university: 'Purdue',
        year: '2005',
      },
    ],
    bio: 'Dr. Alexander Kim is an aerospace engineering expert specializing in aircraft design and propulsion systems. He has worked on NASA projects and brings cutting-edge research to the classroom.',
    specializations: ['Aerodynamics', 'Propulsion', 'Space Technology'],
    officeHours: 'Mon-Fri: 2:00 PM - 4:00 PM',
    achievements: [
      {
        title: 'NASA Collaboration Award',
        description: 'Recognized for contributions to space technology research',
        year: '2023',
        issuedBy: 'NASA'
      }
    ],
    staffRoom: 'B-420',
    seatNo: '22',
    floor: '4th',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alexander',
  },
  {
    teacherId: 'T022',
    fullName: 'Ms. Lisa Wong',
    phone: '555-0122',
    email: 'lisa.wong@school.edu',
    designation: 'Music Instructor',
    department: 'Music',
    qualification: 'M.Mus',
    experience: 9,
    joiningDate: '15/03/2015',
    dateOfBirth: '08/11/1985',
    subjects: ['Piano', 'Music Theory', 'Composition'],
    education: [
      {
        degree: 'M.Mus in Performance',
        college: 'Juilliard School',
        university: 'Juilliard',
        year: '2015',
      },
      {
        degree: 'B.Mus in Piano Performance',
        college: 'Eastman School of Music',
        university: 'Eastman',
        year: '2011',
      },
    ],
    bio: 'Lisa Wong is an accomplished pianist and composer who has performed internationally. She teaches both classical and contemporary music and encourages student creativity.',
    specializations: ['Piano Performance', 'Music Composition', 'Music Technology'],
    officeHours: 'Tue-Thu: 1:00 PM - 3:00 PM',
    achievements: [
      {
        title: 'Performance Excellence Award',
        description: 'Recognized for outstanding musical performances',
        year: '2022',
        issuedBy: 'Music Academy'
      }
    ],
    staffRoom: 'Music Hall',
    seatNo: '1',
    floor: 'Ground',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
  },
  {
    teacherId: 'T015',
    fullName: 'Dr. Shaurya Singh',
    phone: '555-0115',
    email: 'shaurya.singh@school.edu',
    designation: 'Associate Professor of Biotechnology',
    department: 'Biotechnology',
    qualification: 'Ph.D. in Molecular Biology',
    experience: 12,
    joiningDate: '10/01/2012',
    dateOfBirth: '15/07/1985',
    subjects: ['Molecular Biology', 'Genetic Engineering', 'Bioinformatics', 'Cell Biology'],
    education: [
      {
        degree: 'Ph.D. in Molecular Biology',
        college: 'University of Delhi',
        university: 'Delhi University',
        year: '2012',
      },
      {
        degree: 'M.Sc. in Biotechnology',
        college: 'Indian Institute of Technology, Bombay',
        university: 'IIT Bombay',
        year: '2008',
      },
      {
        degree: 'B.Sc. in Life Sciences',
        college: 'Delhi University',
        university: 'Delhi University',
        year: '2006',
      },
    ],
    bio: 'Dr. Shaurya Singh is a renowned biotechnology researcher with expertise in genetic engineering and molecular biology. He has published over 45 research papers and has been awarded multiple grants for his groundbreaking work in CRISPR technology and gene therapy.',
    specializations: ['CRISPR Gene Editing', 'Gene Therapy', 'Molecular Cloning', 'Bioinformatics'],
    officeHours: 'Mon-Wed-Fri: 2:00 PM - 4:00 PM',
    achievements: [
      {
        title: 'National Science Award',
        description: 'Recognized for outstanding contributions to biotechnology research',
        year: '2023',
        issuedBy: 'Ministry of Science and Technology'
      },
      {
        title: 'Young Scientist Award',
        description: 'Awarded for innovative research in gene therapy',
        year: '2020',
        issuedBy: 'Indian National Science Academy'
      },
      {
        title: 'Best Research Paper Award',
        description: 'For groundbreaking work on CRISPR applications',
        year: '2022',
        issuedBy: 'International Biotechnology Society'
      }
    ],
    research: [
      {
        title: 'CRISPR-Based Therapeutic Approaches for Genetic Disorders',
        journal: 'Nature Biotechnology',
        year: '2023',
        link: 'https://example.com/crispr-therapy',
        authors: ['Shaurya Singh', 'Priya Sharma', 'Rajesh Kumar']
      },
      {
        title: 'Novel Gene Editing Techniques for Cancer Treatment',
        journal: 'Journal of Molecular Medicine',
        year: '2022',
        link: 'https://example.com/gene-cancer',
        authors: ['Shaurya Singh', 'Anjali Verma']
      },
      {
        title: 'Bioinformatics Analysis of Genetic Mutations in Rare Diseases',
        journal: 'Bioinformatics Today',
        year: '2021',
        link: 'https://example.com/bioinformatics-mutations',
        authors: ['Shaurya Singh', 'Vikram Patel', 'Neha Gupta']
      },
      {
        title: 'Molecular Mechanisms of CRISPR-Cas9 Off-Target Effects',
        journal: 'Genome Research',
        year: '2020',
        link: 'https://example.com/crispr-offtarget',
        authors: ['Shaurya Singh']
      }
    ],
    projects: [
      {
        title: 'Development of CRISPR-Based Gene Therapy for Sickle Cell Disease',
        description: 'A collaborative project to develop and test CRISPR-based treatments for sickle cell disease with potential clinical applications',
        year: '2021-2025',
        role: 'Principal Investigator',
        fundingAgency: 'Department of Biotechnology, India'
      },
      {
        title: 'Bioinformatics Platform for Genomic Data Analysis',
        description: 'Creating an advanced bioinformatics platform for analyzing large-scale genomic datasets',
        year: '2020-2024',
        role: 'Co-Investigator',
        fundingAgency: 'National Institute of Biomedical Genomics'
      },
      {
        title: 'Student Research Initiative in Molecular Biology',
        description: 'Mentoring undergraduate and graduate students in cutting-edge molecular biology research',
        year: '2019-Present',
        role: 'Project Lead'
      }
    ],
    staffRoom: 'B-305',
    seatNo: '18',
    floor: '3rd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shaurya',
  },
  {
    teacherId: 'T016',
    fullName: 'Dr. Tannu Verma',
    phone: '555-0116',
    email: 'tannu.verma@school.edu',
    designation: 'Assistant Professor of Environmental Science',
    department: 'Environmental Science',
    qualification: 'Ph.D. in Environmental Science',
    experience: 8,
    joiningDate: '15/06/2016',
    dateOfBirth: '22/09/1990',
    subjects: ['Environmental Ecology', 'Climate Change', 'Sustainable Development', 'Conservation Biology'],
    education: [
      {
        degree: 'Ph.D. in Environmental Science',
        college: 'University of British Columbia',
        university: 'UBC',
        year: '2016',
      },
      {
        degree: 'M.Sc. in Environmental Science',
        college: 'University of Delhi',
        university: 'Delhi University',
        year: '2012',
      },
      {
        degree: 'B.Sc. in Environmental Science',
        college: 'Delhi University',
        university: 'Delhi University',
        year: '2010',
      },
    ],
    bio: 'Dr. Tannu Verma is a passionate environmental scientist dedicated to climate change research and sustainable development. She has conducted extensive fieldwork in various ecosystems and has published research on biodiversity conservation and climate resilience.',
    specializations: ['Climate Change Mitigation', 'Biodiversity Conservation', 'Renewable Energy', 'Sustainable Development'],
    officeHours: 'Tue-Thu: 11:00 AM - 1:00 PM',
    achievements: [
      {
        title: 'Green Earth Award',
        description: 'Recognized for outstanding contributions to environmental conservation',
        year: '2023',
        issuedBy: 'Global Environmental Foundation'
      },
      {
        title: 'Young Environmental Scientist Award',
        description: 'For innovative research in climate change adaptation',
        year: '2021',
        issuedBy: 'Environmental Science Society'
      }
    ],
    research: [
      {
        title: 'Climate Resilience Strategies for Coastal Ecosystems',
        journal: 'Environmental Research Letters',
        year: '2023',
        link: 'https://example.com/coastal-resilience',
        authors: ['Tannu Verma', 'Arun Kumar', 'Priya Singh']
      },
      {
        title: 'Biodiversity Patterns in Himalayan Forests Under Climate Change',
        journal: 'Journal of Ecology and Conservation',
        year: '2022',
        link: 'https://example.com/himalayan-biodiversity',
        authors: ['Tannu Verma', 'Rajesh Nair']
      },
      {
        title: 'Renewable Energy Transition in Developing Nations',
        journal: 'Sustainable Energy Reviews',
        year: '2021',
        link: 'https://example.com/renewable-transition',
        authors: ['Tannu Verma', 'Vikram Singh', 'Neha Patel']
      }
    ],
    projects: [
      {
        title: 'Himalayan Ecosystem Monitoring and Conservation Project',
        description: 'Long-term monitoring of Himalayan ecosystems to assess climate change impacts and develop conservation strategies',
        year: '2018-2026',
        role: 'Principal Investigator',
        fundingAgency: 'Ministry of Environment, Forest and Climate Change'
      },
      {
        title: 'Community-Based Climate Adaptation Program',
        description: 'Implementing climate adaptation strategies with local communities in vulnerable regions',
        year: '2020-2024',
        role: 'Co-Investigator'
      }
    ],
    staffRoom: 'C-210',
    seatNo: '11',
    floor: '2nd',
    status: TeacherStatus.AVAILABLE,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tannu',
  },
  {
    teacherId: 'T017',
    fullName: 'Prof. Kamal Mehta',
    phone: '555-0117',
    email: 'kamal.mehta@school.edu',
    designation: 'Professor of Materials Science and Engineering',
    department: 'Materials Science',
    qualification: 'Ph.D. in Materials Science',
    experience: 16,
    joiningDate: '20/08/2008',
    dateOfBirth: '08/03/1982',
    subjects: ['Materials Science', 'Nanotechnology', 'Polymer Science', 'Materials Characterization'],
    education: [
      {
        degree: 'Ph.D. in Materials Science and Engineering',
        college: 'Indian Institute of Technology, Madras',
        university: 'IIT Madras',
        year: '2008',
      },
      {
        degree: 'M.Tech in Materials Science',
        college: 'Indian Institute of Technology, Delhi',
        university: 'IIT Delhi',
        year: '2004',
      },
      {
        degree: 'B.Tech in Metallurgical Engineering',
        college: 'National Institute of Technology, Rourkela',
        university: 'NIT Rourkela',
        year: '2002',
      },
    ],
    bio: 'Professor Kamal Mehta is a leading expert in nanotechnology and advanced materials. He has developed novel nanomaterials with applications in electronics, energy storage, and biomedical devices. His research has resulted in multiple patents and collaborations with international institutions.',
    specializations: ['Nanotechnology', 'Graphene and 2D Materials', 'Polymer Nanocomposites', 'Materials Characterization'],
    officeHours: 'Mon-Fri: 1:00 PM - 3:00 PM',
    achievements: [
      {
        title: 'National Materials Science Award',
        description: 'Lifetime achievement award for contributions to materials science and nanotechnology',
        year: '2023',
        issuedBy: 'Indian National Academy of Engineering'
      },
      {
        title: 'Innovation in Materials Award',
        description: 'For development of novel nanomaterials with commercial applications',
        year: '2022',
        issuedBy: 'Materials Research Society'
      },
      {
        title: 'International Patent Award',
        description: 'Multiple patents in nanotechnology and advanced materials',
        year: '2021',
        issuedBy: 'World Intellectual Property Organization'
      }
    ],
    research: [
      {
        title: 'Graphene-Based Nanocomposites for High-Performance Electronics',
        journal: 'Advanced Materials',
        year: '2023',
        link: 'https://example.com/graphene-electronics',
        authors: ['Kamal Mehta', 'Arjun Singh', 'Meera Sharma']
      },
      {
        title: 'Development of Biodegradable Polymer Nanocomposites',
        journal: 'Polymer Science and Engineering',
        year: '2022',
        link: 'https://example.com/biodegradable-polymers',
        authors: ['Kamal Mehta', 'Sanjay Kumar', 'Priya Nair']
      },
      {
        title: 'Nanoparticles for Drug Delivery Applications',
        journal: 'Nanotechnology Today',
        year: '2021',
        link: 'https://example.com/nanoparticles-drug',
        authors: ['Kamal Mehta', 'Vikram Patel', 'Anjali Gupta']
      },
      {
        title: 'Advanced Characterization Techniques for Nanomaterials',
        journal: 'Journal of Materials Characterization',
        year: '2020',
        link: 'https://example.com/characterization-techniques',
        authors: ['Kamal Mehta']
      }
    ],
    projects: [
      {
        title: 'Development of Graphene-Based Energy Storage Devices',
        description: 'Creating next-generation batteries and supercapacitors using graphene and other 2D materials',
        year: '2020-2025',
        role: 'Principal Investigator',
        fundingAgency: 'Department of Science and Technology'
      },
      {
        title: 'Nanomedical Devices for Targeted Drug Delivery',
        description: 'Developing nanoparticle-based systems for precise drug delivery in cancer therapy',
        year: '2019-2024',
        role: 'Co-Investigator',
        fundingAgency: 'Indian Council of Medical Research'
      },
      {
        title: 'Sustainable Nanomaterials for Environmental Applications',
        description: 'Research on eco-friendly nanomaterials for water purification and pollution control',
        year: '2021-Present',
        role: 'Project Lead'
      }
    ],
    staffRoom: 'A-405',
    seatNo: '22',
    floor: '4th',
    status: TeacherStatus.IN_CLASS,
    role: UserRole.TEACHER,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kamal',
  },
];

export const MOCK_STUDENTS: Student[] = [
  {
    studentId: 'S001',
    fullName: 'Alice Johnson',
    phone: '555-0201',
    email: 'alice.johnson@student.edu',
    course: 'Computer Science',
    section: 'A',
    year: 2024,
    semester: 5,
    branch: 'Computer Science',
    specialization: 'Artificial Intelligence',
    fatherName: 'Robert Johnson',
    motherName: 'Mary Johnson',
    dateOfBirth: '15/08/2003',
    college: 'Tech University - Main Campus',
    enrollNo: 'EN-2024001',
    universityRollNo: '2024001',
    classRollNo: '12',
    highSchoolPercentage: 85.5,
    intermediatePercentage: 78.2,
    status: 'Active',
    role: UserRole.STUDENT,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice',
  },
  {
    studentId: 'S002',
    fullName: 'Bob Williams',
    phone: '555-0202',
    email: 'bob.williams@student.edu',
    course: 'Mechanical Engineering',
    section: 'C',
    year: 2024,
    semester: 3,
    branch: 'Mechanical',
    specialization: 'Robotics',
    fatherName: 'James Williams',
    motherName: 'Sarah Williams',
    dateOfBirth: '22/03/2004',
    college: 'Tech University - Engineering Campus',
    enrollNo: 'EN-2024002',
    universityRollNo: '2024002',
    classRollNo: '08',
    highSchoolPercentage: 92.0,
    intermediatePercentage: 88.5,
    status: 'Active',
    role: UserRole.STUDENT,
    profileImage: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob',
  },
];
